In [93]:
import pandas as pd

## 건물대장부에서 부산시 데이터만 추출

In [94]:
# col_name_data = pd.read_excel('../Data/Building/컬럼.xls', engine='xlrd')
# col_name_list = list(col_name_data['데이터구조'])[1:]

In [95]:
# data = pd.read_csv('../Data/Building/mart_djy_03.txt', encoding='cp949', sep='|', header=None, names=col_name_list)

C:\Users\choji\AppData\Local\Temp\ipykernel_229880\3651677984.py:1: DtypeWarning: Columns (14,15,31,58,59,60,61,62,67,76) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('../Data/Building/mart_djy_03.txt', encoding='cp949', sep='|', header=None, names=col_name_list)

필요없는 컬럼 삭제

In [96]:
# data.drop(columns=data.columns[:5], inplace=True)
# data.drop(columns=data.columns[2:21], inplace=True)
# data.drop(columns=['구조_코드', '용적_률_산정_연면적(㎡)'], inplace=True)
# data.drop(columns=data.columns[8:16], inplace=True)
# data.drop(columns=data.columns[11:40], inplace=True)
# null_percentage = (data.isnull().sum() / len(data)) * 100
# columns_to_drop = null_percentage[null_percentage >= 20].index
# data = data.drop(columns=columns_to_drop)

In [101]:
# busan_data = data[data['대지_위치'].str.contains('부산')]

In [103]:
# busan_data.reset_index(drop=True, inplace=True)

In [105]:
# busan_data.to_csv('../Data/Building/Busan_Building_preprocessing.csv', index=False)

----------------

## 부산시 건물대장부

In [106]:
busan_data = pd.read_csv('../Data/Building/Busan_Building_preprocessing.csv')

In [107]:
busan_data

,대지_위치,도로명_대지_위치,건축_면적(㎡),건폐_율(%),연면적(㎡),용적_률(%),구조_코드_명,기타_구조,높이(m),지상_층_수,지하_층_수,생성_일자
0,부산광역시 사하구 괴정동 351-3번지,부산광역시 사하구 까치고개로 20,0.00,61.88,54.14,122.09,블록구조,블럭조,6.7,2,0,20100624
1,부산광역시 사하구 괴정동 354-101번지,부산광역시 사하구 까치고개로 10-5,0.00,0.00,149.09,0.00,블록구조,블럭조,0.0,2,1,20100624
2,부산광역시 사하구 구평동 435-36번지,부산광역시 사하구 두송로 125,0.00,0.00,29.75,0.00,블록구조,조적조,0.0,1,0,20100619
3,부산광역시 사하구 구평동 435-36번지,부산광역시 사하구 두송로 125,0.00,0.00,29.75,0.00,블록구조,조적조,0.0,1,0,20100619
4,부산광역시 사하구 구평동 435-36번지,부산광역시 사하구 두송로 125,0.00,0.00,29.75,0.00,블록구조,조적조,0.0,1,0,20100619
...,...,...,...,...,...,...,...,...,...,...,...,...
361749,부산광역시 사하구 신평동 11-278번지,부산광역시 사하구 장평로326번길 9-21,26.00,89.65,48.50,167.24,벽돌구조,조적조,0.0,2,0,20220225
361750,부산광역시 사하구 장림동 604-38번지,부산광역시 사하구 장림시장5길 284,0.00,0.00,49.06,0.00,블록구조,블럭조,0.0,2,0,20220225
361751,부산광역시 사하구 괴정동 193-151번지,,0.00,0.00,41.56,0.00,블록구조,블럭조,0.0,1,0,20220225
361752,부산광역시 사하구 당리동 344-9번지,부산광역시 사하구 마하로31번길 56-2,0.00,35.25,137.48,49.23,블록구조,블럭조,7.5,2,1,20220221
361753,부산광역시 해운대구 반여동 1026-15번지,부산광역시 해운대구 선수촌로 144,460.54,59.89,3246.48,376.06,철근콘크리트구조,철근콘크리트구조,25.4,8,1,20220223

In [109]:
busan_data.describe()

,건축_면적(㎡),건폐_율(%),연면적(㎡),용적_률(%),높이(m),지상_층_수,지하_층_수,생성_일자
count,3.617540e+05,361754.000000,3.617540e+05,361754.000000,361754.000000,361754.000000,361754.000000,3.617540e+05
mean,1.986783e+02,21.817432,9.807315e+02,61.143191,7.518852,2.583590,0.187249,2.019012e+07
std,6.441918e+03,106.517912,1.396377e+05,137.787791,325.090531,3.439998,0.485475,2.893180e+04
min,-3.600000e+00,-0.860000,0.000000e+00,0.000000,-7.300000,0.000000,0.000000,2.009032e+07
25%,3.966000e+01,0.000000,5.157000e+01,0.000000,0.000000,1.000000,0.000000,2.017102e+07
50%,7.328000e+01,0.000000,1.295900e+02,0.000000,0.000000,2.000000,0.000000,2.019071e+07
75%,1.296000e+02,55.280000,3.267000e+02,97.460000,8.800000,3.000000,0.000000,2.021050e+07
max,3.836635e+06,59163.900000,8.337438e+07,30427.000000,87600.000000,101.000000,69.000000,2.024020e+07

In [110]:
busan_data[busan_data['연면적(㎡)'] == 0]

,대지_위치,도로명_대지_위치,건축_면적(㎡),건폐_율(%),연면적(㎡),용적_률(%),구조_코드_명,기타_구조,높이(m),지상_층_수,지하_층_수,생성_일자
146,부산광역시 서구 암남동 16-6번지,부산광역시 서구 성산길 47-17,9.24,0.0000,0.0,0.00,벽돌구조,벽돌구조,0.00,1,0,20110414
186,부산광역시 동구 초량동 859-37번지,부산광역시 동구 영초윗길62번길 16,0.00,0.0000,0.0,0.00,일반목구조,목조,0.00,1,0,20110414
1627,부산광역시 남구 용호동 486-62번지,부산광역시 남구 용호로 186,54.02,59.4300,0.0,118.86,블록구조,블럭조,7.00,2,1,20170811
3410,부산광역시 남구 감만동 34-28번지,부산광역시 남구 석포로58번길 12-8,0.00,0.0000,0.0,0.00,블록구조,시멘트블럭조,0.00,1,0,20170811
4847,부산광역시 남구 문현동 332-41번지,부산광역시 남구 동제당로 122-13,0.00,0.0000,0.0,0.00,NaN,NaN,0.00,0,0,20170811
...,...,...,...,...,...,...,...,...,...,...,...,...
357886,부산광역시 금정구 서동 302-128번지,,0.00,0.0000,0.0,0.00,벽돌구조,벽돌조,11.00,3,0,20231114
357975,부산광역시 남구 대연동 1731-13번지,부산광역시 남구 유엔로157번길 88,0.00,0.0000,0.0,0.00,철근콘크리트구조,철근콘크리트조,8.40,3,1,20230519
358000,부산광역시 수영구 망미동 413-11번지,부산광역시 수영구 과정로 44-1,64.07,63.7512,0.0,0.00,벽돌구조,벽돌조,7.20,2,1,20230519
358918,부산광역시 사상구 학장동 288-7번지,부산광역시 사상구 가야대로196번길 63,0.00,0.0000,0.0,0.00,철근콘크리트구조,철근콘크리트조,11.20,3,0,20171205
359881,부산광역시 사상구 학장동 820-1번지,부산광역시 사상구 대동로 84,0.00,0.0000,0.0,0.00,철근콘크리트구조,철근콘크리트조,63.85,21,1,20190601