## 라이브러리

In [333]:
import pandas as pd

-----------

## 대피소

In [334]:
Shelter_data = pd.read_csv('../../Data/Shelter/Busan_shelter_pre.csv')
Shelter_data2 = pd.read_csv('../../Data/Shelter/shelter_preprcessing.csv')

In [354]:
Shelter_data.head()

,운영상태,도로명전체주소,소재지전체주소,시설면적(㎡),최대수용인원,위도(EPSG4326),경도(EPSG4326),자치구,동읍면
0,사용중지,"부산광역시 중구 충장대로 20, 부산세관 (중앙동4가)",부산광역시 중구 중앙동4가 17번지 26호 부산세관,991.0,1201,35.104484,129.038980,중구,중앙동4가
1,사용중,"부산광역시 중구 충장대로 11 (중앙동4가, 무역회관빌딩)",부산광역시 중구 중앙동4가 87번지 7호,1205.0,1460,35.105545,129.037712,중구,중앙동4가
2,사용중,부산광역시 중구 중앙대로 지하 83 (중앙동4가),부산광역시 중구 중앙동4가 26번지 3호,2543.0,3082,35.105161,129.036082,중구,중앙동4가
3,사용중,"부산광역시 중구 중앙대로 지하 17 (중앙동6가, 광복지하도상가)",부산광역시 중구 중앙동6가 9번지 1호,3666.0,4443,35.099288,129.036327,중구,중앙동6가
4,사용중,부산광역시 중구 중앙대로 63 (중앙동3가),부산광역시 중구 중앙동3가 1번지,2054.0,2489,35.103395,129.036145,중구,중앙동3가

In [336]:
Shelter_data.drop(columns=['시설위치(지상/지하)', '좌표정보(X)',	'좌표정보(Y)'], inplace=True)

In [337]:
Shelter_data = Shelter_data[Shelter_data['소재지전체주소'].str.contains('부산광역시')]

In [338]:
Shelter_data['자치구'] = Shelter_data['소재지전체주소'].str.split().str[1]
Shelter_data['동읍면'] = Shelter_data['소재지전체주소'].str.split().str[2]

In [339]:
Shelter_data2.head()

,주소,경도,위도,수용가능인원수,대피소 lenght,대피소구분,대피소 height,도로명주소,관리기관
0,부산광역시 기장군 기장읍 연화리 276-3,129.223647,35.216698,500,500,도로변,28,부산 기장군 기장읍 연화리 284-32,기장군청
1,부산광역시 기장군 기장읍 연화리 193,129.224870,35.219080,300,250,도로변,17,부산 기장군 기장읍 연화리 193,기장군청
2,부산광역시 기장군 기장읍 당사리 507,129.209860,35.186086,400,300,도로변,15,부산 기장군 기장읍 당사리 510,기장군청
3,부산광역시 기장군 기장읍 대변리 383,129.228664,35.226286,300,350,민간건축물,15,부산광역시 기장군 기장읍 대변로 149,기장군청
4,부산광역시 기장군 기장읍 대변리 450,129.226290,35.223734,300,75,도로변,20,부산 기장군 기장읍 대변리 450,기장군청

-----------------

## 지하철

In [340]:
Subway_data = pd.read_csv('../../Data/Subway/Subway_preprocessing.csv')

In [341]:
Subway_data.head()

   역명                 지번주소         위도          경도   승하차인원_합계
0  괴정  부산광역시 사하구 괴정동 934-3  35.099734  128.991905   545404.0
1  교대  부산광역시 연제구 거제동 72-25  35.195820  129.079995   301985.0
2  구서    부산광역시 금정구 구서동 475  35.245085  129.090869   546261.0
3  남산  부산광역시 금정구 남산동 136-1  35.265644  129.090881   298138.0
4  남포    부산광역시 중구 남포동1가 11  35.097884  129.034585  1081561.0

--------------------------

## 학교

In [342]:
School_data = pd.read_csv('../../Data/School/school_final.csv')

In [343]:
School_data.head()

         학교명                                    도로명주소         위도          경도
0     기장초등학교                     부산광역시 기장군 기장읍 읍내로 69  35.245772  129.212766
1   성일여자고등학교                        부산광역시 사하구 다대로 161  35.089500  128.980063
2   한국과학영재학교  부산광역시 부산진구 백양관문로 105-47 (당감동. 한국과학영재학교)  35.165200  129.025784
3     서감초등학교                         부산광역시 사상구 괘감로 64  35.157820  128.982060
4  부일외국어고등학교                     부산광역시 사하구 감천로73번길 36  35.090736  129.002560

---------------------------------------------------

## 병원

In [344]:
hospital_data = pd.read_csv('../../Data/Hospital/hospital_final.csv')

In [345]:
hospital_data.head()

                                                  주소          경도         위도
0                            부산광역시 서구 감천로 262, (암남동)  129.013959  35.080964
1                        부산광역시 서구 대신공원로 26, (동대신동3가)  129.017539  35.120168
2                          부산광역시 서구 구덕로 179, (아미동1가)  129.018803  35.100848
3  부산광역시 부산진구 복지로 75, 진사로83번길 75, 진사로83번길 81, 1층(...  129.020861  35.145517
4                          부산광역시 북구 낙동대로 1786, (구포동)  129.004724  35.209713

-----------------

## 주택

In [346]:
Density_data = pd.read_csv('../../Data/Population_density/Population_density_final.csv')

In [347]:
Density_data.head()

                         주소   세대수         위도          경도
0  부산광역시 강서구 명지오션시티10로 17     652  35.087487  128.897986
1  부산광역시 강서구 명지오션시티10로 16    1102  35.085491  128.897777
2  부산광역시 강서구 명지오션시티11로 51    1112  35.085599  128.901800
3   부산광역시 강서구 명지오션시티2로 71    1124  35.083142  128.901149
4   부산광역시 강서구 명지오션시티11로 22   1256  35.083129  128.897766

-------------------------

## 인구 수

In [348]:
Population_data = pd.read_csv('../../Data/Population/population_final.csv')

In [349]:
Population_data.head()

  자치구  읍면동   세대 수   인구 수
0  중구   소계  23925  42609
1  중구  중앙동   2226   3380
2  중구  동광동   1729   2998
3  중구  대청동   3502   6351
4  중구  보수동   5953  10760

------------------

## 부산광역시 건축대장부

In [350]:
Building_data = pd.read_csv('../../Data/Building/Building_final.csv')

In [351]:
Building_data.head()

,지번주소,도로명주소,건축_면적(㎡),건폐_율(%),연면적(㎡),용적_률(%),구조_코드_명,기타_구조,높이(m),지상_층_수,지하_층_수,생성_일자
0,부산광역시 사하구 괴정동 351-3번지,부산광역시 사하구 까치고개로 20,0.0,61.88,54.14,122.09,블록구조,블럭조,6.7,2,0,20100624
1,부산광역시 사하구 괴정동 354-101번지,부산광역시 사하구 까치고개로 10-5,0.0,0.00,149.09,0.00,블록구조,블럭조,0.0,2,1,20100624
2,부산광역시 사하구 구평동 435-36번지,부산광역시 사하구 두송로 125,0.0,0.00,29.75,0.00,블록구조,조적조,0.0,1,0,20100619
3,부산광역시 사하구 구평동 435-36번지,부산광역시 사하구 두송로 125,0.0,0.00,29.75,0.00,블록구조,조적조,0.0,1,0,20100619
4,부산광역시 사하구 구평동 435-36번지,부산광역시 사하구 두송로 125,0.0,0.00,29.75,0.00,블록구조,조적조,0.0,1,0,20100619

------------------------

# 부산광역시 인구수 별 대피소 분석

In [352]:
Population_data

     자치구  읍면동   세대 수   인구 수
0     중구   소계  23925  42609
1     중구  중앙동   2226   3380
2     중구  동광동   1729   2998
3     중구  대청동   3502   6351
4     중구  보수동   5953  10760
..   ...  ...    ...    ...
216  기장군  기장읍  25598  53378
217  기장군  장안읍   4732   8949
218  기장군  정관읍  31904  82889
219  기장군  일광면  10728  25983
220  기장군  철마면   3891   7975

[221 rows x 4 columns]

In [353]:
Shelter_data

,운영상태,도로명전체주소,소재지전체주소,시설면적(㎡),최대수용인원,위도(EPSG4326),경도(EPSG4326),자치구,동읍면
0,사용중지,"부산광역시 중구 충장대로 20, 부산세관 (중앙동4가)",부산광역시 중구 중앙동4가 17번지 26호 부산세관,991.0,1201,35.104484,129.038980,중구,중앙동4가
1,사용중,"부산광역시 중구 충장대로 11 (중앙동4가, 무역회관빌딩)",부산광역시 중구 중앙동4가 87번지 7호,1205.0,1460,35.105545,129.037712,중구,중앙동4가
2,사용중,부산광역시 중구 중앙대로 지하 83 (중앙동4가),부산광역시 중구 중앙동4가 26번지 3호,2543.0,3082,35.105161,129.036082,중구,중앙동4가
3,사용중,"부산광역시 중구 중앙대로 지하 17 (중앙동6가, 광복지하도상가)",부산광역시 중구 중앙동6가 9번지 1호,3666.0,4443,35.099288,129.036327,중구,중앙동6가
4,사용중,부산광역시 중구 중앙대로 63 (중앙동3가),부산광역시 중구 중앙동3가 1번지,2054.0,2489,35.103395,129.036145,중구,중앙동3가
...,...,...,...,...,...,...,...,...,...
1403,사용중,부산광역시 기장군 일광읍 해송1로 33(일광 신도시 비스타 동원 2차),부산광역시 기장군 일광읍 이천리 944 일광 신도시 비스타 동원 2차,39940.0,48412,35.268303,129.230447,기장군,일광읍
1404,사용중,부산광역시 기장군 일광읍 해빛로 39-15(일광자이푸르지오 1단지),부산광역시 기장군 일광읍 삼성리 783 일광자이푸르지오 1단지,20544.0,24901,35.266460,129.222743,기장군,일광읍
1405,사용중,부산광역시 기장군 일광읍 해빛1로 62(한신더휴센트럴포레 1단지),부산광역시 기장군 일광읍 삼성리 794 한신더휴센트럴포레 1단지,16001.0,19395,35.261375,129.223269,기장군,일광읍
1406,사용중,부산광역시 기장군 일광읍 해빛3로 62(한신더휴센트럴포레 2단지),부산광역시 기장군 일광읍 삼성리 792 한신더휴센트럴포레 2단지,23282.0,28220,35.262103,129.219903,기장군,일광읍
1407,사용중,부산광역시 기장군 일광읍 해빛로 29(일광자이푸르지오 2단지),부산광역시 기장군 일광읍 삼성리 785 일광자이푸르지오 2단지,35143.0,42597,35.266701,129.224693,기장군,일광읍